### PR TITLE
Refactor Freya output file opening

### PR DESCRIPTION
**Pull request by elecro**
Move the output file opening into its own method and
also move the header printing to a separate method.

### CODE REVIEW

**Comment by zherczeg** [comment]
Is this just style change?

**Comment by galpeter** [comment]
yes, but it's a step forward for my other improvement which will be uploaded in a day or two.

**Comment by elecro** [comment]
yes, but it's a step forward for my other improvement which will be uploaded in a day or two.

**Comment by zherczeg** [comment]
OK. LGTM

**Pull request merged**
